spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:train
    username: sa
    password: password
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect