name: Docker Image CI / Kubernetes Deployment CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USER}}
      REPO_NAME: ${{github.event.repository.name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        id: prepare
        run: |
          echo "docker_image=${DOCKER_USERNAME}/${REPO_NAME}" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{steps.prepare.outputs.docker_image}}:${{github.ref_name}},${{steps.prepare.outputs.docker_image}}:${{github.ref_name}}-${{steps.prepare.outputs.sha_short}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Add Kubernetes deployment steps
      - name: Kubernetes Config
        uses: Azure/k8s-set-context@v4
        with:
          kubeconfig: ${{secrets.KUBE_CONFIG}}

      - name: Kubernetes Deploy
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          namespace: spring-boot
          manifests: |
            kubernetes/deployment.yml
            kubernetes/service.yml
            kubernetes/ingress.yml
          images: |
            ${{steps.prepare.outputs.docker_image}}:${{github.ref_name}}-${{steps.prepare.outputs.sha_short}}